# Configuration for LunarLander-v3
n_train_steps: 1500000

ppo_params:
  learning_rate: 2.5e-4
  n_steps: 4096
  batch_size: 128
  n_epochs: 20
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  verbose: 1

policy:
  name: "MlpPolicy"
  kwargs:
    activation_fn: "ReLU"
    net_arch:
      pi: [256, 256]
      vf: [256, 256]
